version: "3.2"
services:
  backend_services:
    build:
      context: ./server
    depends_on:
      - postgres
      - redis
    networks:
      - network
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sintetik
      - SECRET=${SECRET}
    ports:
      - "3001:3001"
    volumes:
      - /home/kaithleen/Desktop/Backend/server:/usr/src/app
    container_name: mainservice
    tty: true

  feed_service:
    build:
      context: ./server2
    depends_on:
      - postgres
      - redis
    networks:
      - network
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sintetik
    ports:
      - "3002:3002"
    # volumes:
    #   - /home/kaithleen/Desktop/Backend/server2:/usr/src/app
    container_name: feedservice
    tty: true

  redis:
    restart: always
    image: "redis:7.0.0"
    networks:
      - network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../redis_mount:/bitnami/redis/data
    container_name: redis

  postgres:
    restart: always
    image: postgres:13-alpine
    networks:
      - network
    volumes:
      - ../db_mount:/var/lib/postgresql/data
      - ./db_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sintetik
    container_name: projectdb

networks:
  network:

    
