### Signup
POST http://localhost:3001/user/signup HTTP/1.1
content-type: application/json

{
    "email": "kai.ling25@besquare.com.my",
    "password": "Abcd1234!@",
    "confirm_password": "Abcd1234!@"
}
### Login
POST http://localhost:3001/user/login HTTP/1.1
content-type: application/json

{
    "email": "kai.ling2@besquare.com.my",
    "password": "AAAbc1234!!_"

}
### reset userbalance
PATCH http://localhost:3001/account/resetBalance HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
    "reset_balance" :"true"
}

### get userbalance
GET http://localhost:3001/account/getBalance HTTP/1.1
content-type: application/json
Authorization: Bearer 

### get userTransaction
GET http://localhost:3001/account/getTransaction HTTP/1.1
content-type: application/json
Authorization: Bearer 

### get userContractSummary
GET http://localhost:3001/account/getContractSummary HTTP/1.1
content-type: application/json
Authorization: Bearer 

### reset password
PATCH http://localhost:3001/account/resetPassword HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiI0ZjZhZGY3YjNkM2NiOTZiMWQ4MjQ0ZGJjOGJiNGRlYiIsImNvbnRlbnQiOiJiMSJ9LCJpYXQiOjE2Njk4Nzk4NDQsImV4cCI6MTY2OTk2NjI0NH0.RcBa0F2UqqSpOP5b-li8OrBBUDJ-OBmVsoZaLqKUM1XkYQ-CMGqA78RTLsBPkm-AD36AJmnQYdwfM_sre5sWCM-JW6MZ7N04OAUphnod3ZVedUYsu1ECUIFGU89LL-MitZRgsR2-30uArp3UN_ubSpt-Dgz-jnsubrMx5bE-mdM0JJ4L2khHQ0jWY7Rog-d_ekO1hDuIoJmNxRs3nsnHIxtJZa9BtQFFY_rlx3pJ_YRRncCUHMSxVUper6_rYFtUana2CQhunaZ-uCKHgKbtCTkU9fttwvUq3-Yko5jPAIiB5T3VjM27tqt5BvbA6vxIJYsazxXZQ3H0WlDbItJlsEYx0xTLzWUZ7_As__3P4Gf46QE6mtgn6kHLIaUZwA9DepzT2s0FQiO0JlK4L-keagkNAiaXP3p5pRw0D76Fm1PGV0Aj91g4tERGqr3RVU3BflpAaZmEtH4uxpXYZ5VdfPTrry2jj_FBYzA8Sg4h3MIfEqWgYsFcQNSbLIDmUPEKN-HVQGKMTBwRz3oClY-5LP4rJAZpcWEvttm_V_gmP9m0qFzaJPBxfzo9xWwSqhDIAGfhIyTN6_wBFZp8pXrFAcVm8pUu3RLsmjmAv90VQHoFtDWRrURn2VMEwnpIWOjIs2hnD8vvZfPG2aHQ-Sf_HIuOaHFg-QIpBE2eKfLw0Zw

{
    "old_password": "Abcd1234!@",
    "new_password": "AAAbc1234!!_",
    "new_password_confirmation": "AAAbc1234!!_"
}

### get user details
GET http://localhost:3001/account/getUserDetails HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiI0ZjZhZGY3YjNkM2NiOTZiMWQ4MjQ0ZGJjOGJiNGRlYiIsImNvbnRlbnQiOiJiMSJ9LCJpYXQiOjE2Njk4Nzk4NDQsImV4cCI6MTY2OTk2NjI0NH0.RcBa0F2UqqSpOP5b-li8OrBBUDJ-OBmVsoZaLqKUM1XkYQ-CMGqA78RTLsBPkm-AD36AJmnQYdwfM_sre5sWCM-JW6MZ7N04OAUphnod3ZVedUYsu1ECUIFGU89LL-MitZRgsR2-30uArp3UN_ubSpt-Dgz-jnsubrMx5bE-mdM0JJ4L2khHQ0jWY7Rog-d_ekO1hDuIoJmNxRs3nsnHIxtJZa9BtQFFY_rlx3pJ_YRRncCUHMSxVUper6_rYFtUana2CQhunaZ-uCKHgKbtCTkU9fttwvUq3-Yko5jPAIiB5T3VjM27tqt5BvbA6vxIJYsazxXZQ3H0WlDbItJlsEYx0xTLzWUZ7_As__3P4Gf46QE6mtgn6kHLIaUZwA9DepzT2s0FQiO0JlK4L-keagkNAiaXP3p5pRw0D76Fm1PGV0Aj91g4tERGqr3RVU3BflpAaZmEtH4uxpXYZ5VdfPTrry2jj_FBYzA8Sg4h3MIfEqWgYsFcQNSbLIDmUPEKN-HVQGKMTBwRz3oClY-5LP4rJAZpcWEvttm_V_gmP9m0qFzaJPBxfzo9xWwSqhDIAGfhIyTN6_wBFZp8pXrFAcVm8pUu3RLsmjmAv90VQHoFtDWRrURn2VMEwnpIWOjIs2hnD8vvZfPG2aHQ-Sf_HIuOaHFg-QIpBE2eKfLw0Zw

### edit user details
PATCH http://localhost:3001/account/editUserDetails HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiI0ZjZhZGY3YjNkM2NiOTZiMWQ4MjQ0ZGJjOGJiNGRlYiIsImNvbnRlbnQiOiJiMSJ9LCJpYXQiOjE2Njk4Nzk4NDQsImV4cCI6MTY2OTk2NjI0NH0.RcBa0F2UqqSpOP5b-li8OrBBUDJ-OBmVsoZaLqKUM1XkYQ-CMGqA78RTLsBPkm-AD36AJmnQYdwfM_sre5sWCM-JW6MZ7N04OAUphnod3ZVedUYsu1ECUIFGU89LL-MitZRgsR2-30uArp3UN_ubSpt-Dgz-jnsubrMx5bE-mdM0JJ4L2khHQ0jWY7Rog-d_ekO1hDuIoJmNxRs3nsnHIxtJZa9BtQFFY_rlx3pJ_YRRncCUHMSxVUper6_rYFtUana2CQhunaZ-uCKHgKbtCTkU9fttwvUq3-Yko5jPAIiB5T3VjM27tqt5BvbA6vxIJYsazxXZQ3H0WlDbItJlsEYx0xTLzWUZ7_As__3P4Gf46QE6mtgn6kHLIaUZwA9DepzT2s0FQiO0JlK4L-keagkNAiaXP3p5pRw0D76Fm1PGV0Aj91g4tERGqr3RVU3BflpAaZmEtH4uxpXYZ5VdfPTrry2jj_FBYzA8Sg4h3MIfEqWgYsFcQNSbLIDmUPEKN-HVQGKMTBwRz3oClY-5LP4rJAZpcWEvttm_V_gmP9m0qFzaJPBxfzo9xWwSqhDIAGfhIyTN6_wBFZp8pXrFAcVm8pUu3RLsmjmAv90VQHoFtDWRrURn2VMEwnpIWOjIs2hnD8vvZfPG2aHQ-Sf_HIuOaHFg-QIpBE2eKfLw0Zw

{
    "firstname":"limmm1",
    "lastname":"kath",
    "gender": "Female",
    "residence":"Malaysia",
    "occupation":"Student",
    "age":"19",
    "education":"Tertiary"

}

### send reset password link
POST http://localhost:3001/user/password-reset HTTP/1.1
content-type: application/json

{
    "email": "kai.ling@besquare.com.my"

}

### reset password
POST http://localhost:3001/user/password-reset/2/cd013345b7605c2c790f3503139011667466e78f4385a0462c558dbb84624694 HTTP/1.1
content-type: application/json

{
    "password":"Abcd1234!@",
    "confirm_password":"Abcd1234!@"
}

### logout
POST http://localhost:3001/account/logout HTTP/1.1
content-type: application/json
Authorization: Bearer 