## Signup
POST http://localhost:3001/user/signup HTTP/1.1
content-type: application/json

{
    "email": "kai.ling2@besquare.com.my",
    "password": "Abcd123!"
}
### Login
POST http://localhost:3001/user/login HTTP/1.1
content-type: application/json

{
    "email": "kai.ling@besquare.com.my",
    "password": "AAAbcd1234!!_"

}
### reset userbalance
POST http://localhost:3001/account/resetBalance HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiI5OGRlY2UyMmNlZDEwYjI1YzRhMDFjZWI4ZjU3M2VmNyIsImNvbnRlbnQiOiI0MiJ9LCJpYXQiOjE2Njg2NzEwNTMsImV4cCI6MTY2ODc1NzQ1M30.rPtLUVuT9B4vzTNYDfw2IrFqjHDBndvODzuHImMPteKIDIZGEprvbmpmKabd0J6ckAdp57hq1lc1MrbQHJgpyILSnsQEQ7_gN8BLonh2htxMEHm7jUBeRrJs2kHJESWdfbF0B-H6aSBokPWjMh9IunWVxSnY_gAAaFO_OAkUwqrCCvqZg6VPMOfj6ySgjdqFVuLD16goP3RK09gl9SzUe_zKQ0vhS9tT0UFZTD9qOq0Xcej1GO6zSrtD7OYVHEy45hUO80iUhHN3XAVCvUWioqKjJip3VZM34SKZR1Du7bE8BumNOBMWFyoSQIFaljcyPPucaeyVtdTxr67STZAFDjLjDEfaEXKQICLyRH7k5j898f0Br2QYIoJypoDQ94D0tYNEUCRv6-dB6e1UEbzdKeqoiuhaoB9-6lTluDuRRv47sDkpfmmlBJ7Ifuh-4anJMeOFNjiDWQPThblk04qFt4OyQy8PJTnze4E-DiYgnm8g6Y-CrrllRNkLoIQ2jnM4IR57-zgfcUoZNeTmL-e8H2YsguV-jHzPiHbCXvDbCitnw0pLtyVKbQjZHoHre9yTRUTHOJRPIGfVGNG6i_MB_I1A6Ut7i2Z8A1vjv61ujz1ANhi2jrEk8qrZBqv0y1Ca6wu1fIti6TzaTkt5w9vEwhHs0xc-g3ZFGjA2MPjTqGQ

{
    "reset_balance" :"true"
}

### get userbalance
GET http://localhost:3001/account/getBalance HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiI5OGRlY2UyMmNlZDEwYjI1YzRhMDFjZWI4ZjU3M2VmNyIsImNvbnRlbnQiOiI0MiJ9LCJpYXQiOjE2Njg2NzEwNTMsImV4cCI6MTY2ODc1NzQ1M30.rPtLUVuT9B4vzTNYDfw2IrFqjHDBndvODzuHImMPteKIDIZGEprvbmpmKabd0J6ckAdp57hq1lc1MrbQHJgpyILSnsQEQ7_gN8BLonh2htxMEHm7jUBeRrJs2kHJESWdfbF0B-H6aSBokPWjMh9IunWVxSnY_gAAaFO_OAkUwqrCCvqZg6VPMOfj6ySgjdqFVuLD16goP3RK09gl9SzUe_zKQ0vhS9tT0UFZTD9qOq0Xcej1GO6zSrtD7OYVHEy45hUO80iUhHN3XAVCvUWioqKjJip3VZM34SKZR1Du7bE8BumNOBMWFyoSQIFaljcyPPucaeyVtdTxr67STZAFDjLjDEfaEXKQICLyRH7k5j898f0Br2QYIoJypoDQ94D0tYNEUCRv6-dB6e1UEbzdKeqoiuhaoB9-6lTluDuRRv47sDkpfmmlBJ7Ifuh-4anJMeOFNjiDWQPThblk04qFt4OyQy8PJTnze4E-DiYgnm8g6Y-CrrllRNkLoIQ2jnM4IR57-zgfcUoZNeTmL-e8H2YsguV-jHzPiHbCXvDbCitnw0pLtyVKbQjZHoHre9yTRUTHOJRPIGfVGNG6i_MB_I1A6Ut7i2Z8A1vjv61ujz1ANhi2jrEk8qrZBqv0y1Ca6wu1fIti6TzaTkt5w9vEwhHs0xc-g3ZFGjA2MPjTqGQ

### get userTransaction
GET http://localhost:3001/account/getTransaction HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiIxNzNhYmM2OTkzYjdhZDIwMzViODMwMmE0N2ViY2M5ZiIsImNvbnRlbnQiOiI3MyJ9LCJpYXQiOjE2Njg2NzE4NjAsImV4cCI6MTY2ODc1ODI2MH0.ubxyjNu0F0gmJ_8a29FJNqk-yQf91GGbRFpDux-m-_WfZd3CQhQkEv-yQt3clGMnmNOHWLIN1iqESbxotSfZtXE-tpWfh9bWkPbbbGJ3EuH2sAbzYtRDrLnJ7FKB4vtowmAi76hoZA-NyZHd9P5iT4nYNz45lAXWUy6qrAYbi8lSAJzH31own-9daIxjA4eIiFkmPDk5628Ng2ECUhmrPWGgIY2h1LUkyFVghpKIH-_hegtzi5PgUcYXoZuVBnveZ1vgJ5tJkKVv_8oJh-q8wPm_H5YCU83lpexoalM9w5vXeWR7Yl3eVj1CO3Kvc11nHWRJt4oK7gSkRCbwyygwaVWVBj_f5FbhR3mlgEFBFNBwKdRJHJ8ieCRVYTcM88M2gd5jhtmuB9QhqBc4_7y9S8ZGhiC5W5tsMW8Szfd4vd4akmIs6EgfVbc_qVcMn9QFmXWxK_IMSWmMtQ1EZCd4UFYBzBjnbYA9mSWN9TWrGn3zXqIJ9DIwOZuK3p6NQq9E9UEWkso4_KdSNXKyHYq5OY-jSMlMaRgG7nN-rLW-w_jGEG-VkLGeN_DvenTpN8Gkh4QmHxugAvINtn_qIukVAyNR892NS6yD48YXjm4BLxve39HB_hPg2QO36MwEGWKPSwZ-zSlHrviHooa-FmMObE3hQIDgInrbwMuCu7Y5ap8

### get userContractSummary
GET http://localhost:3001/account/getContractSummary HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiIxNzNhYmM2OTkzYjdhZDIwMzViODMwMmE0N2ViY2M5ZiIsImNvbnRlbnQiOiI3MyJ9LCJpYXQiOjE2Njg2NzE4NjAsImV4cCI6MTY2ODc1ODI2MH0.ubxyjNu0F0gmJ_8a29FJNqk-yQf91GGbRFpDux-m-_WfZd3CQhQkEv-yQt3clGMnmNOHWLIN1iqESbxotSfZtXE-tpWfh9bWkPbbbGJ3EuH2sAbzYtRDrLnJ7FKB4vtowmAi76hoZA-NyZHd9P5iT4nYNz45lAXWUy6qrAYbi8lSAJzH31own-9daIxjA4eIiFkmPDk5628Ng2ECUhmrPWGgIY2h1LUkyFVghpKIH-_hegtzi5PgUcYXoZuVBnveZ1vgJ5tJkKVv_8oJh-q8wPm_H5YCU83lpexoalM9w5vXeWR7Yl3eVj1CO3Kvc11nHWRJt4oK7gSkRCbwyygwaVWVBj_f5FbhR3mlgEFBFNBwKdRJHJ8ieCRVYTcM88M2gd5jhtmuB9QhqBc4_7y9S8ZGhiC5W5tsMW8Szfd4vd4akmIs6EgfVbc_qVcMn9QFmXWxK_IMSWmMtQ1EZCd4UFYBzBjnbYA9mSWN9TWrGn3zXqIJ9DIwOZuK3p6NQq9E9UEWkso4_KdSNXKyHYq5OY-jSMlMaRgG7nN-rLW-w_jGEG-VkLGeN_DvenTpN8Gkh4QmHxugAvINtn_qIukVAyNR892NS6yD48YXjm4BLxve39HB_hPg2QO36MwEGWKPSwZ-zSlHrviHooa-FmMObE3hQIDgInrbwMuCu7Y5ap8


### reset password
POST http://localhost:3001/account/resetPassword HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiI5OGRlY2UyMmNlZDEwYjI1YzRhMDFjZWI4ZjU3M2VmNyIsImNvbnRlbnQiOiI0MiJ9LCJpYXQiOjE2Njg2NzEwNTMsImV4cCI6MTY2ODc1NzQ1M30.rPtLUVuT9B4vzTNYDfw2IrFqjHDBndvODzuHImMPteKIDIZGEprvbmpmKabd0J6ckAdp57hq1lc1MrbQHJgpyILSnsQEQ7_gN8BLonh2htxMEHm7jUBeRrJs2kHJESWdfbF0B-H6aSBokPWjMh9IunWVxSnY_gAAaFO_OAkUwqrCCvqZg6VPMOfj6ySgjdqFVuLD16goP3RK09gl9SzUe_zKQ0vhS9tT0UFZTD9qOq0Xcej1GO6zSrtD7OYVHEy45hUO80iUhHN3XAVCvUWioqKjJip3VZM34SKZR1Du7bE8BumNOBMWFyoSQIFaljcyPPucaeyVtdTxr67STZAFDjLjDEfaEXKQICLyRH7k5j898f0Br2QYIoJypoDQ94D0tYNEUCRv6-dB6e1UEbzdKeqoiuhaoB9-6lTluDuRRv47sDkpfmmlBJ7Ifuh-4anJMeOFNjiDWQPThblk04qFt4OyQy8PJTnze4E-DiYgnm8g6Y-CrrllRNkLoIQ2jnM4IR57-zgfcUoZNeTmL-e8H2YsguV-jHzPiHbCXvDbCitnw0pLtyVKbQjZHoHre9yTRUTHOJRPIGfVGNG6i_MB_I1A6Ut7i2Z8A1vjv61ujz1ANhi2jrEk8qrZBqv0y1Ca6wu1fIti6TzaTkt5w9vEwhHs0xc-g3ZFGjA2MPjTqGQ

{
    "old_password": "Abcd123!",
    "new_password": "AAAbcd1234!!_",
    "new_password_confirmation": "AAAbcd1234!!_"
}

### get user details
GET http://localhost:3001/account/getUserDetails HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI1IiwiaWF0IjoxNjY4NDg1NzE5LCJleHAiOjE2Njg1NzIxMTl9.MbusUTWxbUXySHyyGCntFJ9jhGQfEnQ7VOmYJ13iaq0

### edit user details
POST http://localhost:3001/account/editUserDetails HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI1IiwiaWF0IjoxNjY4NDg1NzE5LCJleHAiOjE2Njg1NzIxMTl9.MbusUTWxbUXySHyyGCntFJ9jhGQfEnQ7VOmYJ13iaq0

{
    "firstname":"limmm",
    "lastname":"kath",
    "gender": "Female",
    "residence":"Malaysia",
    "occupation":"Student",
    "age":"19",
    "education":"Tertiary"

}

### send reset password link
POST http://localhost:3001/user/password-reset HTTP/1.1
content-type: application/json

{
    "email": "kai.ling@besquare.com.my"

}

### reset password
POST http://localhost:3001/user/password-reset/2/a9dcec76424ce4412549dad9138b22ddb338769772731958a71e4a5319493218 HTTP/1.1
content-type: application/json

{
    "password":"Abcd1234!@",
    "confirm_password":"Abcd1234!@"
}


