## Signup
POST http://localhost:3001/user/signup HTTP/1.1
content-type: application/json

{
    "email": "kai.ling1@besquare.com.my",
    "password": "Abcd1234!@"
}
### Login
POST http://localhost:3001/user/login HTTP/1.1
content-type: application/json

{
    "email": "kai.ling@besquare.com.my",
    "password": "AAAbc1234!!_"

}
### reset userbalance
POST http://localhost:3001/account/resetBalance HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJkYzY3YTJjY2NiZTdiODk0MTM5YTMzNTQyNDc2NmJhNyIsImNvbnRlbnQiOiJmZiJ9LCJpYXQiOjE2Njg5OTY3MzgsImV4cCI6MTY2OTA4MzEzOH0.H2iIed_hs4w63p-9_ALP4kzt9WDekcyOiciBFXwmhv0sVJ2MoVTY7AiXA-EwFOjMG2E1WzU82Di67XNlsh417wXbX6a86rW0uhX2zDQkcbObMEtK4S-4TkJKY28IE0MR1njumwoz2OYvSidCNUh8ELv7MPn5xnVG00RC8WlmOCAGj_iOjS_wYYMj44Yt6qI-MPztwIxCrl0vqxm3BXBtGpsUvXzfWM8K9PRBGMJ99r6qsUAwt7Ejf4NqPoLr3sMTz03HFZl0EDoRJ5En27hRo51Aru5JI1vJMlD_a19-AM_tB6WOvrvl6AWvP2i_v9IO8h1sJVkiGL2TbUzf6VcMWt63UzM1ZemDi7IgjCljcCspeLLLa0zAJMsg39kFC0vPctOORkLaEQgYoNikT4Kb8FgOewJdItMO8OTiCEbJVkQdY8XDCqVpBgk6ZbBgNMfwMnPa__dDG-sa8N6jQIQSzueHoNGUvwrie3YnSdjBTNtNI9Xui06JLVzb3LEHS3zFo8-0c2ke_zSIjfmc_a_NzjVdYbsb3v6mKVkVgCIh03q52QiweT5UBAIyJ8W4eHngHhXcwmJLSkRA-aWtXL-SbLUzftLzVGHYX34Em1QGYlrhsZObDGLEnjQLqaVXN0hPJOxrMK0MJMJlCVtxxnvjaKcNHc5ib8JyQUobk1FUDmU

{
    "reset_balance" :"true"
}

### get userbalance
GET http://localhost:3001/account/getBalance HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJlMjBhNzdjZTk3YzRiOTMzMmFiNTVjMGMzMjkyNzUxOCIsImNvbnRlbnQiOiIyNSJ9LCJpYXQiOjE2Njg5OTY3ODIsImV4cCI6MTY2OTA4MzE4Mn0.UPN9xhEAd69iDfN0f0u8Z6geRLMMcnelN9_B8j6DL4Eibxxq5ZhNwsXyo_NPUuT4H9ifYFnA_cjOQj987aSPuIJxf0F9rayZysjeOSzNN9j2BrLGqJc2lWoj4KWtz6tlCc5-Mp5lwvk5I0pbbBWAhmelM6FmfUqywoD8esbUs-K6pxbdoMk1WPd3I0NqiJ0O5if7Xi8tHIriA4XaGx-oHl7j1YYH8UH6vntjHoyjgkd4inSFF9jNn_KQJ_LM1vClMA5RRSBVdRDuMt_z5qbrOgB5npnVycxO31Mq1UyuBgSJzY8nvi4dtBGDM1WxfBFM7ffcbUXjQIWfifVrrnBCHx8hVnvuter30utbIfWBEHwnjTSPi_2SZ0knvrD6cwm9A-X3ppfVK1IjI0O0sfr1IMVQxeaTEYbp8jHt2dRHaBoL1ZEgBnCKW2DK4h43OzE16nDyEyH7OsmhvEcr6KxymcYJZEc0Ld7DshiqYkJGVbrPwo7TfUgnzABJzd5nG3aLD7OJ20CVVCKksu0WvjI8oF4tUu5mLXuctYQVlsU6kZiRA-IVAZpDgGaarJqs36wYrFTtAMG3TSFzJeoZJZzcMHW8TWSizmQk78Xj4eTMrIjK5S_6JPpYLwJJ8OgdElKuaGmtuBlCUakUbSVvJdQsuTlrTs1MFhbShc-wJW-Y_Js

### get userTransaction
GET http://localhost:3001/account/getTransaction HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJlMjBhNzdjZTk3YzRiOTMzMmFiNTVjMGMzMjkyNzUxOCIsImNvbnRlbnQiOiIyNSJ9LCJpYXQiOjE2Njg5OTY3ODIsImV4cCI6MTY2OTA4MzE4Mn0.UPN9xhEAd69iDfN0f0u8Z6geRLMMcnelN9_B8j6DL4Eibxxq5ZhNwsXyo_NPUuT4H9ifYFnA_cjOQj987aSPuIJxf0F9rayZysjeOSzNN9j2BrLGqJc2lWoj4KWtz6tlCc5-Mp5lwvk5I0pbbBWAhmelM6FmfUqywoD8esbUs-K6pxbdoMk1WPd3I0NqiJ0O5if7Xi8tHIriA4XaGx-oHl7j1YYH8UH6vntjHoyjgkd4inSFF9jNn_KQJ_LM1vClMA5RRSBVdRDuMt_z5qbrOgB5npnVycxO31Mq1UyuBgSJzY8nvi4dtBGDM1WxfBFM7ffcbUXjQIWfifVrrnBCHx8hVnvuter30utbIfWBEHwnjTSPi_2SZ0knvrD6cwm9A-X3ppfVK1IjI0O0sfr1IMVQxeaTEYbp8jHt2dRHaBoL1ZEgBnCKW2DK4h43OzE16nDyEyH7OsmhvEcr6KxymcYJZEc0Ld7DshiqYkJGVbrPwo7TfUgnzABJzd5nG3aLD7OJ20CVVCKksu0WvjI8oF4tUu5mLXuctYQVlsU6kZiRA-IVAZpDgGaarJqs36wYrFTtAMG3TSFzJeoZJZzcMHW8TWSizmQk78Xj4eTMrIjK5S_6JPpYLwJJ8OgdElKuaGmtuBlCUakUbSVvJdQsuTlrTs1MFhbShc-wJW-Y_Js

### get userContractSummary
GET http://localhost:3001/account/getContractSummary HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJlMjBhNzdjZTk3YzRiOTMzMmFiNTVjMGMzMjkyNzUxOCIsImNvbnRlbnQiOiIyNSJ9LCJpYXQiOjE2Njg5OTY3ODIsImV4cCI6MTY2OTA4MzE4Mn0.UPN9xhEAd69iDfN0f0u8Z6geRLMMcnelN9_B8j6DL4Eibxxq5ZhNwsXyo_NPUuT4H9ifYFnA_cjOQj987aSPuIJxf0F9rayZysjeOSzNN9j2BrLGqJc2lWoj4KWtz6tlCc5-Mp5lwvk5I0pbbBWAhmelM6FmfUqywoD8esbUs-K6pxbdoMk1WPd3I0NqiJ0O5if7Xi8tHIriA4XaGx-oHl7j1YYH8UH6vntjHoyjgkd4inSFF9jNn_KQJ_LM1vClMA5RRSBVdRDuMt_z5qbrOgB5npnVycxO31Mq1UyuBgSJzY8nvi4dtBGDM1WxfBFM7ffcbUXjQIWfifVrrnBCHx8hVnvuter30utbIfWBEHwnjTSPi_2SZ0knvrD6cwm9A-X3ppfVK1IjI0O0sfr1IMVQxeaTEYbp8jHt2dRHaBoL1ZEgBnCKW2DK4h43OzE16nDyEyH7OsmhvEcr6KxymcYJZEc0Ld7DshiqYkJGVbrPwo7TfUgnzABJzd5nG3aLD7OJ20CVVCKksu0WvjI8oF4tUu5mLXuctYQVlsU6kZiRA-IVAZpDgGaarJqs36wYrFTtAMG3TSFzJeoZJZzcMHW8TWSizmQk78Xj4eTMrIjK5S_6JPpYLwJJ8OgdElKuaGmtuBlCUakUbSVvJdQsuTlrTs1MFhbShc-wJW-Y_Js

### reset password
POST http://localhost:3001/account/resetPassword HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJlMjBhNzdjZTk3YzRiOTMzMmFiNTVjMGMzMjkyNzUxOCIsImNvbnRlbnQiOiIyNSJ9LCJpYXQiOjE2Njg5OTY3ODIsImV4cCI6MTY2OTA4MzE4Mn0.UPN9xhEAd69iDfN0f0u8Z6geRLMMcnelN9_B8j6DL4Eibxxq5ZhNwsXyo_NPUuT4H9ifYFnA_cjOQj987aSPuIJxf0F9rayZysjeOSzNN9j2BrLGqJc2lWoj4KWtz6tlCc5-Mp5lwvk5I0pbbBWAhmelM6FmfUqywoD8esbUs-K6pxbdoMk1WPd3I0NqiJ0O5if7Xi8tHIriA4XaGx-oHl7j1YYH8UH6vntjHoyjgkd4inSFF9jNn_KQJ_LM1vClMA5RRSBVdRDuMt_z5qbrOgB5npnVycxO31Mq1UyuBgSJzY8nvi4dtBGDM1WxfBFM7ffcbUXjQIWfifVrrnBCHx8hVnvuter30utbIfWBEHwnjTSPi_2SZ0knvrD6cwm9A-X3ppfVK1IjI0O0sfr1IMVQxeaTEYbp8jHt2dRHaBoL1ZEgBnCKW2DK4h43OzE16nDyEyH7OsmhvEcr6KxymcYJZEc0Ld7DshiqYkJGVbrPwo7TfUgnzABJzd5nG3aLD7OJ20CVVCKksu0WvjI8oF4tUu5mLXuctYQVlsU6kZiRA-IVAZpDgGaarJqs36wYrFTtAMG3TSFzJeoZJZzcMHW8TWSizmQk78Xj4eTMrIjK5S_6JPpYLwJJ8OgdElKuaGmtuBlCUakUbSVvJdQsuTlrTs1MFhbShc-wJW-Y_Js

{
    "old_password": "Abcd1234!@",
    "new_password": "AAAbc1234!!_",
    "new_password_confirmation": "AAAbc1234!!_"
}

### get user details
GET http://localhost:3001/account/getUserDetails HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJlMjBhNzdjZTk3YzRiOTMzMmFiNTVjMGMzMjkyNzUxOCIsImNvbnRlbnQiOiIyNSJ9LCJpYXQiOjE2Njg5OTY3ODIsImV4cCI6MTY2OTA4MzE4Mn0.UPN9xhEAd69iDfN0f0u8Z6geRLMMcnelN9_B8j6DL4Eibxxq5ZhNwsXyo_NPUuT4H9ifYFnA_cjOQj987aSPuIJxf0F9rayZysjeOSzNN9j2BrLGqJc2lWoj4KWtz6tlCc5-Mp5lwvk5I0pbbBWAhmelM6FmfUqywoD8esbUs-K6pxbdoMk1WPd3I0NqiJ0O5if7Xi8tHIriA4XaGx-oHl7j1YYH8UH6vntjHoyjgkd4inSFF9jNn_KQJ_LM1vClMA5RRSBVdRDuMt_z5qbrOgB5npnVycxO31Mq1UyuBgSJzY8nvi4dtBGDM1WxfBFM7ffcbUXjQIWfifVrrnBCHx8hVnvuter30utbIfWBEHwnjTSPi_2SZ0knvrD6cwm9A-X3ppfVK1IjI0O0sfr1IMVQxeaTEYbp8jHt2dRHaBoL1ZEgBnCKW2DK4h43OzE16nDyEyH7OsmhvEcr6KxymcYJZEc0Ld7DshiqYkJGVbrPwo7TfUgnzABJzd5nG3aLD7OJ20CVVCKksu0WvjI8oF4tUu5mLXuctYQVlsU6kZiRA-IVAZpDgGaarJqs36wYrFTtAMG3TSFzJeoZJZzcMHW8TWSizmQk78Xj4eTMrIjK5S_6JPpYLwJJ8OgdElKuaGmtuBlCUakUbSVvJdQsuTlrTs1MFhbShc-wJW-Y_Js

### edit user details
POST http://localhost:3001/account/editUserDetails HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOnsiaXYiOiJlMjBhNzdjZTk3YzRiOTMzMmFiNTVjMGMzMjkyNzUxOCIsImNvbnRlbnQiOiIyNSJ9LCJpYXQiOjE2Njg5OTY3ODIsImV4cCI6MTY2OTA4MzE4Mn0.UPN9xhEAd69iDfN0f0u8Z6geRLMMcnelN9_B8j6DL4Eibxxq5ZhNwsXyo_NPUuT4H9ifYFnA_cjOQj987aSPuIJxf0F9rayZysjeOSzNN9j2BrLGqJc2lWoj4KWtz6tlCc5-Mp5lwvk5I0pbbBWAhmelM6FmfUqywoD8esbUs-K6pxbdoMk1WPd3I0NqiJ0O5if7Xi8tHIriA4XaGx-oHl7j1YYH8UH6vntjHoyjgkd4inSFF9jNn_KQJ_LM1vClMA5RRSBVdRDuMt_z5qbrOgB5npnVycxO31Mq1UyuBgSJzY8nvi4dtBGDM1WxfBFM7ffcbUXjQIWfifVrrnBCHx8hVnvuter30utbIfWBEHwnjTSPi_2SZ0knvrD6cwm9A-X3ppfVK1IjI0O0sfr1IMVQxeaTEYbp8jHt2dRHaBoL1ZEgBnCKW2DK4h43OzE16nDyEyH7OsmhvEcr6KxymcYJZEc0Ld7DshiqYkJGVbrPwo7TfUgnzABJzd5nG3aLD7OJ20CVVCKksu0WvjI8oF4tUu5mLXuctYQVlsU6kZiRA-IVAZpDgGaarJqs36wYrFTtAMG3TSFzJeoZJZzcMHW8TWSizmQk78Xj4eTMrIjK5S_6JPpYLwJJ8OgdElKuaGmtuBlCUakUbSVvJdQsuTlrTs1MFhbShc-wJW-Y_Js

{
    "firstname":"limmm",
    "lastname":"kath",
    "gender": "Female",
    "residence":"Malaysia",
    "occupation":"Student",
    "age":"19",
    "education":"Tertiary"

}

### send reset password link
POST http://localhost:3001/user/password-reset HTTP/1.1
content-type: application/json

{
    "email": "kai.ling@besquare.com.my"

}

### reset password
POST http://localhost:3001/user/password-reset/2/cd013345b7605c2c790f3503139011667466e78f4385a0462c558dbb84624694 HTTP/1.1
content-type: application/json

{
    "password":"Abcd1234!@",
    "confirm_password":"Abcd1234!@"
}


