# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline to DigitalOcean server

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: CI Setup in the server folder
        run: |
          cd server
          npm install

      - name: Create .env file
        run: |
          touch .env
          echo 'SECRET=${{ secrets.SECRET }}' >> .env
          echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> .env
          echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' >> .env
          echo 'PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}' >> .env
          echo 'PGADMIN_DEFAULT_PASSWORD=${{ secrets.POSTGRES_DEFAULT_PASSWORD }}' >> .env
          echo 'REDIS_PORT=${{ secrets.REDIS_PORT }}' >> .env
          cat .env

      - name: Running Docker compose
        run: |
          docker compose --env-file .env up -d --build
