# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline to DigitalOcean server

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Running Docker compose
        run: |
          docker compose --env-file .env up --build

      - name: CI Setup in the server folder
        run: |
          cd server
          npm install

      - name: CI Exec in the server folder
        run: |
          npm run build

      - name: CI Setup in the server2 folder
        run: |
          cd ../server2
          npm install
          pip install -r requirements.txt

      - name: CI Exec in the server2 folder
        run: |
          npm run build
